# This is a basic workflow to help you get started with Actions

name: Deploy Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: delete .opam
        run: |
          rm *.opam
          
      - name: Install deps
        run: |
          opam install menhir llvm
          opam install . --deps-only --with-doc
          opam depext --install odoc
          opam exec -- dune build @doc
        shell: bash
        
      - name: Deploy odoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
