name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: llvm@11 python@3

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
          
      - name: conf-python
        run: opam install conf-python-3.1.0.0

      - name: Installing deps
        run: opam install . --deps-only --with-doc
        shell: bash
      
      - name: Build docs
        run: |
          rm *.opam
          opam exec -- dune build
          opam exec -- dune build @doc
        shell: bash
        
      - name: Deploy odoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:         
          github_token: ${{ github.token }}
          publish_dir: _build/default/_doc/_html
